version: "3.8"
services:
    #PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./public/build:/var/www/public/build
        ports:
            - 8888:8888
        depends_on:
            - database

    #Database Server
    database:
        image: mysql:8.1.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        volumes:
            - db-data:/var/lib/mysql



volumes:
    db-data: ~
